const mockMatchesData = [
  // Matches for yesterday
  {
    id: 1,
    date: '2024-12-26',
    teamA: 'Liverpool',
    teamB: 'Manchester United',
    score: '2-1',
    league: 'Premier League',
  },
  {
    id: 2,
    date: '2024-12-26',
    teamA: 'Barcelona',
    teamB: 'Real Madrid',
    score: '1-1',
    league: 'La Liga',
  },
  {
    id: 3,
    date: '2024-12-26',
    teamA: 'Juventus',
    teamB: 'Napoli',
    score: '3-2',
    league: 'Serie A',
  },
  {
    id: 4,
    date: '2024-12-26',
    teamA: 'Paris Saint-Germain',
    teamB: 'Marseille',
    score: '4-1',
    league: 'Ligue 1',
  },
  {
    id: 5,
    date: '2024-12-26',
    teamA: 'Bayern Munich',
    teamB: 'Borussia Dortmund',
    score: '2-0',
    league: 'Bundesliga',
  },
  // Matches for today
  {
    id: 6,
    date: '2024-12-27',
    teamA: 'Manchester City',
    teamB: 'Chelsea',
    score: '3-0',
    league: 'Premier League',
  },
  {
    id: 7,
    date: '2024-12-27',
    teamA: 'Atletico Madrid',
    teamB: 'Sevilla',
    score: '2-2',
    league: 'La Liga',
  },
  {
    id: 8,
    date: '2024-12-27',
    teamA: 'AC Milan',
    teamB: 'Inter Milan',
    score: '1-1',
    league: 'Serie A',
  },
  {
    id: 9,
    date: '2024-12-27',
    teamA: 'Lyon',
    teamB: 'Bordeaux',
    score: '2-0',
    league: 'Ligue 1',
  },
  {
    id: 10,
    date: '2024-12-27',
    teamA: 'Schalke',
    teamB: 'Werder Bremen',
    score: '1-3',
    league: 'Bundesliga',
  },
  // Matches for tomorrow
  {
    id: 11,
    date: '2024-12-28',
    teamA: 'Tottenham Hotspur',
    teamB: 'Arsenal',
    score: '',
    league: 'Premier League',
  },
  {
    id: 12,
    date: '2024-12-28',
    teamA: 'Real Betis',
    teamB: 'Valencia',
    score: '',
    league: 'La Liga',
  },
  {
    id: 13,
    date: '2024-12-28',
    teamA: 'Lazio',
    teamB: 'Roma',
    score: '',
    league: 'Serie A',
  },
  {
    id: 14,
    date: '2024-12-28',
    teamA: 'Nice',
    teamB: 'Monaco',
    score: '',
    league: 'Ligue 1',
  },
  {
    id: 15,
    date: '2024-12-28',
    teamA: 'Hoffenheim',
    teamB: 'Bayer Leverkusen',
    score: '',
    league: 'Bundesliga',
  },
];

export default mockMatchesData;
